### ISSUE TITLE
Not updating 'Players connected' for incoming lobby users. 

### ISSUE THREAD

**Issue by micmarty** [dotnet-adepts/multiplayer-games-platform#19]
**'Players connected' counter not updating when new lobby user arrives**

**How to reproduce**
1. Open two separate windows, sign in as different users
2. Create lobby as ```USER_1``` and try to enter the lobby as ```USER_2``` in the second window

**Video demo**
https://streamable.com/9gjf2

**Chrome inspector**
![image](https://user-images.githubusercontent.com/12485656/33223902-8e12ad38-d164-11e7-9546-b9d7d8681373.png)

**Comment by p-kwiatkowski** [comment]
Fixed in: https://github.com/dotnet-adepts/multiplayer-games-platform/commit/c1c414a936c4b6c1201145535cfd44a3556d16b4
